version: '3.8'
services:
  bnf-selenium-hub:
    image: selenium/hub:4.1.2-20220217
    container_name: bnf-selenium-hub
    ports:
      - '4442:4442'
      - '4443:4443'
      - '4444:4444'
    environment:
      # When using headless browser mode, there's no need for the Xvfb server to be started.
      - START_XVFB=false
      # Avoid IPv6 issues in Chrome, see https://stackoverflow.com/a/63310211/486434
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=

  bnf-selenium-chrome:
    image: selenium/node-chrome:4.1.2-20220217
    #container_name: bnf-selenium-chrome
    shm_size: '2gb'
    depends_on:
      - bnf-selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=bnf-selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  bnf-test-runner:
    build: .
    container_name: bnf-test-runner
    depends_on:
      - bnf-selenium-hub
      - bnf-website
      - bnfc-website
    environment:
      - TEAMCITY_VERSION
    volumes:
      - ./:/bnf-gatsby/tests
      - /bnf-gatsby/tests/node_modules/

  bnf-website:
    image: nginx:1.21.6-alpine
    container_name: bnf-website
    environment:
      - NGINX_HOST=bnf-functional-tests.nice.org.uk
    volumes:
      # We expect the built BNF website to have been copied into this bnf-website-build folder.
      # This happens automatically if you run `npm run build:bnf` from the Gatsby folder
      - ./bnf-website-build:/usr/share/nginx/html
    networks:
      default:
        aliases:
          # Make sure the app uses a nice.org.uk domain so that the cookie banner license works
          - bnf-functional-tests.nice.org.uk

  bnfc-website:
    image: nginx:1.21.6-alpine
    container_name: bnfc-website
    environment:
      - NGINX_HOST=bnfc-functional-tests.nice.org.uk
    volumes:
      - ./bnfc-website-build:/usr/share/nginx/html
    networks:
      default:
        aliases:
          - bnfc-functional-tests.nice.org.uk

  mock-api:
    build: https://github.com/nice-digital/mocks-apis.git#main:search-apis
    container_name: mock-api
    networks:
      default:
        aliases:
          # The TC pipeline has a build step that switches between these two urls
          # If the branch == main it will point to the live endpoint otherwise point to alpha
          - beta-search-api.nice.org.uk
          - search-api.nice.org.uk

networks:
  default:
    name: bnf-gatsby-functional-tests
